---
title: "Project Data Cleaning"
author: "Camille Okonkwo"
date: "2024-04-11"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

# Loading MMR Data
```{r}
mmr = read_csv("data/MMR_data/US_MMR_1999_2019_ESTIMATES.csv") |> 
  janitor::clean_names() |> 
  select(-measure_name, -measure_id, -sex_id, -sex_name, -age_group_id, -age_group_name, -metric_id, -metric_name) |> 
  mutate(mmr = val,
         lower_mmr = lower,
         upper_mmr = upper) |> 
  select(-val, -upper, -lower) |> 
  mutate(
    race_group = ifelse(race_group == "Hispanic and any race", "Hispanic", race_group),
    race_group = ifelse(race_group == "Non-Hispanic American Indian and Alaska Native", "American Indian/Alaska Native", race_group),
    race_group = ifelse(race_group == "Non-Hispanic Asian, Native Hawaiian, or Other Pacific Islander", "Asian/Native Hawaiian and Pacific Islander", race_group),
    race_group = ifelse(race_group == "Non-Hispanic Black", "Black", race_group),
    race_group = ifelse(race_group == "Non-Hispanic White", "White", race_group),
    race_group = ifelse(race_group == "All racial and ethnic groups", "All race/ethnicities", race_group)
  )
```

# Loading Poverty Data
```{r}
poverty = read_csv("data/2015_poverty.csv", col_types = cols(
  Location = col_character(),
  Black = col_double(),
  Hispanic = col_double(),
  `Asian/Native Hawaiian and Pacific Islander` = col_double(),
  `American Indian/Alaska Native` = col_double(),
  `Multiple Races` = col_double(),
  White = col_double(),
  Total = col_double()
))

poverty =
  poverty |> 
  select(-`Multiple Races`)

poverty_long =
  poverty |> 
  pivot_longer(cols = c(-Location), names_to = "race_group", values_to = "poverty_rate") |> 
  mutate(race_group = ifelse(race_group == "Total", "All race/ethnicities", race_group),
         Location = ifelse(Location == "United States", "National", Location)) |> 
  janitor::clean_names() |> 
  mutate(year_id = 2015) |> 
  rename(location_name = location)
```

# Merging Datasets
```{r}
mmr_2015 =
  mmr |> 
  filter(year_id == "2015")

merged_data =
  inner_join(mmr_2015, poverty_long, by = intersect(names(mmr_2015), names(poverty_long))) |> 
  mutate(location_id = as.character(location_id))

# adding GIS location_id identifier

mapping = tibble::tibble(
  location_id = c("01", "02", "04", "05", "06", "08", "09", "10", "11", "12", "13", "15", "16",
                  "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "NA", "27", "28",
                  "29", "30", "102", "31", "32", "33", "34", "35", "36", "37", "38", "NA", "39",
                  "40", "41", "42", "44", "NA", "45", "46", "47", "48", "49", "50", "51", "53",
                  "NA", "54", "55", "56"),
  location_name = c("Alabama", "Alaska", "Arizona", "Arkansas", "California", "Colorado",
                    "Connecticut", "Delaware", "District of Columbia", "Florida", "Georgia",
                    "Hawaii", "Idaho", "Illinois", "Indiana", "Iowa", "Kansas", "Kentucky",
                    "Louisiana", "Maine", "Maryland", "Massachusetts", "Michigan", "Midwest Census Region",
                    "Minnesota", "Mississippi", "Missouri", "Montana", "National", "Nebraska",
                    "Nevada", "New Hampshire", "New Jersey", "New Mexico", "New York", "North Carolina",
                    "North Dakota", "Northeast Census Region", "Ohio", "Oklahoma", "Oregon",
                    "Pennsylvania", "Rhode Island", "South Census Region", "South Carolina",
                    "South Dakota", "Tennessee", "Texas", "Utah", "Vermont", "Virginia", "Washington",
                    "West Census Region", "West Virginia", "Wisconsin", "Wyoming")
)

mmr_poverty =
  merged_data |> 
  left_join(mapping, by = "location_name")  |> 
  rename(location_id = location_id.y) |> 
  select(-location_id.x) |> 
  select(location_id, location_name, race_group, year_id, mmr,lower_mmr, upper_mmr, poverty_rate)
```

# Extracting data for Black Population
```{r}
black_mmr_poverty =
  mmr_poverty |> 
  filter(race_group %in% c("Black", "All race/ethnicities"))


write.csv(black_mmr_poverty, "data/black_mmr_poverty_2015.csv", row.names = FALSE)
```

