---
title: "Untitled"
author: "Camille Okonkwo"
date: "2024-04-11"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(purrr)
library(stringr)
```

# Loading 2008-2019 poverty data
```{r}
# Function to load and process CSV files
load_poverty_data = function(directory_path) {
  # Get list of CSV files in the directory
  files = list.files(path = directory_path, pattern = "poverty_\\d{4}\\.csv$", full.names = TRUE)
  
  # Read and process each CSV file
  data_list = purrr::map(files, ~ {
    # Extract year from the file name
    year = as.integer(stringr::str_extract(basename(.x), "\\d{4}"))
    
    # Read the CSV file
    data = read.csv(.x)
    
    # Add a column for the year_id
    data = dplyr::mutate(data, year_id = year)
    
    return(data)
  })
  
  # Merge all data frames into one
  merged_data = dplyr::bind_rows(data_list)
  
  return(merged_data)
}

directory_path = "data/poverty_data/"
poverty = load_poverty_data(directory_path)
```

# Renaming and pivoting the data
```{r}
poverty = poverty |> 
  dplyr::rename(
    "Asian/Native Hawaiian and Pacific Islander" = `Asian.Native.Hawaiian.and.Pacific.Islander`,
    "American Indian/Alaska Native" = `American.Indian.Alaska.Native`
  ) |> 
  dplyr::mutate(
    `White` = as.double(`White`),
    `Black` = as.double(`Black`),
    `Hispanic` = as.double(`Hispanic`),
    `American Indian/Alaska Native` = as.double(`American Indian/Alaska Native`),
    `Asian/Native Hawaiian and Pacific Islander` = as.double(`Asian/Native Hawaiian and Pacific Islander`),
  ) |> 
  dplyr::select(-Multiple.Races, -Footnotes)

poverty_long =
  poverty |> 
  tidyr::pivot_longer(cols = c(-Location, -year_id), names_to = "race_group", values_to = "poverty_rate") |> 
  dplyr::mutate(
    race_group = ifelse(race_group == "Total", "All race/ethnicities", race_group),
    Location = ifelse(Location == "United States", "National", Location)
  ) |> 
  janitor::clean_names() |> 
  dplyr::rename(location_name = location) |> 
  mutate(
    pc_poverty = poverty_rate*100
  ) |> 
  dplyr::mutate(
    pc_poverty = ifelse(is.na(poverty_rate), 0, poverty_rate * 100),
    poverty_rate = ifelse(is.na(poverty_rate), 0, poverty_rate)
  )
```

# Loading MMR Data
```{r}
mmr = read_csv("data/MMR_data/US_MMR_1999_2019_ESTIMATES.csv") |> 
  janitor::clean_names() |> 
  select(-measure_name, -measure_id, -sex_id, -sex_name, -age_group_id, -age_group_name, -metric_id, -metric_name) |> 
  mutate(mmr = val,
         lower_mmr = lower,
         upper_mmr = upper) |> 
  select(-val, -upper, -lower) |> 
  mutate(
    race_group = ifelse(race_group == "Hispanic and any race", "Hispanic", race_group),
    race_group = ifelse(race_group == "Non-Hispanic American Indian and Alaska Native", "American Indian/Alaska Native", race_group),
    race_group = ifelse(race_group == "Non-Hispanic Asian, Native Hawaiian, or Other Pacific Islander", "Asian/Native Hawaiian and Pacific Islander", race_group),
    race_group = ifelse(race_group == "Non-Hispanic Black", "Black", race_group),
    race_group = ifelse(race_group == "Non-Hispanic White", "White", race_group),
    race_group = ifelse(race_group == "All racial and ethnic groups", "All race/ethnicities", race_group)
  )
```

# Merging Datasets
```{r}
mmr_filtered =
  mmr |> 
  dplyr::filter(year_id %in% 2008:2019)

merged_data =
  inner_join(mmr_filtered, poverty_long, by = intersect(names(mmr_filtered), names(poverty_long))) |> 
  mutate(location_id = as.character(location_id))

# adding GIS location_id identifier

mapping = tibble::tibble(
  location_id = c("01", "02", "04", "05", "06", "08", "09", "10", "11", "12", "13", "15", "16",
                  "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "NA", "27", "28",
                  "29", "30", "102", "31", "32", "33", "34", "35", "36", "37", "38", "NA", "39",
                  "40", "41", "42", "44", "NA", "45", "46", "47", "48", "49", "50", "51", "53",
                  "NA", "54", "55", "56"),
  location_name = c("Alabama", "Alaska", "Arizona", "Arkansas", "California", "Colorado",
                    "Connecticut", "Delaware", "District of Columbia", "Florida", "Georgia",
                    "Hawaii", "Idaho", "Illinois", "Indiana", "Iowa", "Kansas", "Kentucky",
                    "Louisiana", "Maine", "Maryland", "Massachusetts", "Michigan", "Midwest Census Region",
                    "Minnesota", "Mississippi", "Missouri", "Montana", "National", "Nebraska",
                    "Nevada", "New Hampshire", "New Jersey", "New Mexico", "New York", "North Carolina",
                    "North Dakota", "Northeast Census Region", "Ohio", "Oklahoma", "Oregon",
                    "Pennsylvania", "Rhode Island", "South Census Region", "South Carolina",
                    "South Dakota", "Tennessee", "Texas", "Utah", "Vermont", "Virginia", "Washington",
                    "West Census Region", "West Virginia", "Wisconsin", "Wyoming")
)

mmr_poverty =
  merged_data |> 
  left_join(mapping, by = "location_name")  |> 
  rename(location_id = location_id.y) |> 
  select(-location_id.x) |> 
  select(location_id, location_name, race_group, year_id, mmr,lower_mmr, upper_mmr, poverty_rate)
```

# Extracting data for Black Population: 2008-2019
```{r}
# Function to filter data and write to CSV for a range of years
filter_and_write_csv_range =
  function(data, start_year, end_year, race_group, output_directory) {
  for (year in start_year:end_year) {
    filtered_data <- data |> dplyr::filter(race_group %in% c("Black", "All race/ethnicities") & year_id == year)
    output_file <- paste0(output_directory, "/black_mmr_poverty_", year, ".csv")
    write.csv(filtered_data, output_file, row.names = FALSE)
  }
}

filter_and_write_csv_range(mmr_poverty, 2008, 2019, "Black", "data")
```

